# Generated by Django 3.1.1 on 2020-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('fecha_instalacion', models.DateTimeField(auto_now_add=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ventilacion', 'ventilacion'), ('ecografia', 'ecografia'), ('cirugia', 'cirugia'), ('monitoreo', 'monitoreo'), ('diagnostico por imagenes', 'diagnostico por imagenes')], max_length=50)),
                ('sector', models.CharField(choices=[('guardia', 'guardia'), ('UTI', 'UTI'), ('UCO', 'UCO'), ('quirofano', 'quirofano'), ('rayos', 'rayos'), ('taller', 'taller')], default='taller', max_length=50)),
                ('fecha_mantenimiento_anual', models.DateTimeField(auto_now=True)),
                ('operativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sector'],
            },
        ),
    ]
