# Generated by Django 3.1.1 on 2020-09-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fecha_mantenimiento_anual',
            field=models.DateField(auto_now=True),
        ),
    ]
