# Generated by Django 3.1.1 on 2020-09-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamiento', '0004_auto_20200915_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstanciaService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('responsable', models.CharField(max_length=50)),
                ('falla', models.CharField(max_length=50)),
                ('observaciones', models.TextField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.equipo')),
            ],
        ),
    ]
