# Generated by Django 3.1.1 on 2020-09-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamiento', '0005_constanciaservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='constanciaservice',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
    ]
